services:
  crm-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${CRM_DB_NAME}
      POSTGRES_USER: ${CRM_DB_USER}
      POSTGRES_PASSWORD: ${CRM_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - crm_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  crm-service:
    build: ./apps/crm-service
    command: >
      sh -c "
      until nc -z crm-db 5432; do sleep 2; done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./apps/crm-service:/app
    ports:
      - "8001:8000"
    environment:
      DB_NAME: ${CRM_DB_NAME}
      DB_USER: ${CRM_DB_USER}
      DB_PASSWORD: ${CRM_DB_PASSWORD}
      DB_HOST: crm-db
      DB_PORT: ${CRM_DB_PORT}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - crm-db
      - kafka

  crm-worker:
    build: ./apps/crm-service
    command: >
      sh -c "
      until nc -z crm-db 5432; do sleep 2; done &&
      python kafka/consumer.py
      "
    volumes:
      - ./apps/crm-service:/app
    environment:
      DB_NAME: ${CRM_DB_NAME}
      DB_USER: ${CRM_DB_USER}
      DB_PASSWORD: ${CRM_DB_PASSWORD}
      DB_HOST: crm-db
      DB_PORT: ${CRM_DB_PORT}
      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - crm-db
      - kafka

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

  user-service:
    build: ./apps/user-service
    command: >
      sh -c "
      until nc -z user-db 5432; do sleep 2; done &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./apps/user-service:/app
    ports:
      - "8002:8000"
    environment:
      DB_NAME: ${USER_DB_NAME}
      DB_USER: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      DB_HOST: user-db
      DB_PORT: ${USER_DB_PORT}
    depends_on:
      - user-db
volumes:
  crm_data:
  user_data: